/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    copy: typeof import('./src/components/ProTable/components/VL/index copy.vue')['default']
    Index2: typeof import('./src/components/ProTable/components/VL/index2.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VL: typeof import('./src/components/ProTable/components/VL/index.vue')['default']
  }
}
